var parameters = {
	urlPbx: "wss://v028.hostedvoice.ch/PBX0/WEBSOCKET/websocket",
	urlAuth: "https://webrtc.persk.es/js/innovaphone/WidgetAuth.php",
	pathPrefix: "js/innovaphone/",
	username: null,
	password: null,
	device: null,
	physicalLocation: null,
	regContext: "0",
	companyName: 'Bouygues E&S Schweiz AG',
	companyStreet: 'Hohlstrasse 188',
	companyCity: '8004, Zürich',
	companyTel: '079 128 21 06',
	companyTrunk: '1234',
	companyFax: '4321',
	companyEmail: 'support.sme@hosteddata.ch',
	supporters: [
		{name: 'Sebastian Perske', shortcut: 'sebastian.perske', phone: '10', img: 'img/sebastian.perske.jpg', 'email': 'sebastian.perske@bouygues-es.com', department: 'System-Engineer'},
		{name: 'Enes Türedi', shortcut: 'enes.tueredi', phone: '20', img: 'img/placeholder.jpg', 'email': 'enes.tueredi@bouygues-es.com', department: 'System-Engineer'},
	],
	status: {
                available: { text: 'Verfügbar', className: 'available', active: true },
                away: { text: 'Abwesend', className: 'not-available', active: false },
                lunch: { text: 'Beim Essen', className: 'not-available', active: false },
                vacation: { text: 'Im Urlaub', className: 'not-available', active: false },
                busy: { text: 'Beschäftigt', className: 'offline', active: false },
                dnd: { text: 'Nicht stören', className: 'offline', active: false },
                closed: { text: 'Offline', className: 'offline', active: false },
       },
};